version: "3"
services:
  server:
    build: ./src/TestSystem.Server
    ports:
      - "5000:8080"
#    depends_on:
#      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"