version: "3"
services:
  server:
    build:
      context: ./src
      dockerfile: TestSystem.Server/Dockerfile
    ports:
      - "8080:32225"
    depends_on:
      - db
      - flyway
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:sqlserver://db -user=SA -password=Your_password123 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
